version: '3.1'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - PRODFILE_ACTIVE=dev
      - DEVTOOLS_PORT=35730
      - SERVER_PORT=80
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'

volumes:
  rabbitmq_data:

