
spring:
  devtools:
    livereload:
      port: ${DEVTOOLS_PORT}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}

server:
  port: ${SERVER_PORT}
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}

